version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Linting"
          command: npm run lint

  test:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: npm install
      - run: 
          name: "Testing"
          command: npm run test

  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Building"
          command: echo "building stage ... "

  deliver:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - run: 
          name: "Deliver"
          command: echo "deliver stage ..."

  deploy:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - run: 
          name: "Deploy"
          command: echo "deploy stage ... "

# Orchestrate our job run sequence
workflows:
  version: 2
  lint-test-build-deliver-deploy:
    jobs:
      - lint
      - test
      - build
      - deliver
      - deploy
