version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Linting"
          command: npm run lint

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: npm install
      - run: 
          name: "Testing"
          command: npm run test

  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: npm install
      - run: 
          name: "Building"
          command: npm run build

# Orchestrate our job run sequence
workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint
      - test
      - build
