version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint-test:
    # Primary container image where all commands run
    docker:
      - image: cimg/node:20.0.0

    # service container image
      - image: cimg/mariadb:10.10.3
        name: db
        environment:
          MARIADB_ROOT_PASSWORD: $DB_ROOT_PW
          MARIADB_DATABASE: $DB_NAME
          MARIADB_USER: $DB_USER
          MARIADB_PASSWORD: $DB_PW
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Install MySQL client"
          command: sudo apt-get update && sudo apt-get install -y mysql-client
      - run:
          name: "Granting privileges"
          command: |
            echo "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PW';" | mysql -h db -u root -p"$DB_ROOT_PW"
      - run:
          name: "Linting"
          command: npm run lint
      - run: 
          name: "Testing"
          command: npm run test

  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Building"
          command: echo "building stage ... "

  deliver:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - run: 
          name: "Deliver"
          command: echo "deliver stage ..."

  deploy:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - run: 
          name: "Deploy"
          command: echo "deploy stage ... "

# Orchestrate our job run sequence
workflows:
  version: 2
  lint-test-build-deliver-deploy:
    jobs:
      - lint-test
      - build
      - deliver
      - deploy
